### ISSUE TITLE
[Feature Request] Support user based beta projects

### ISSUE THREAD

**Issue by Mause** [leonsteinhaeuser/project-beta-automations#12]
**Is your feature request related to a problem? Please describe.**
I want to be able to automate beta projects owned by users

**Describe the solution you'd like**
Add a `user` input field

**Describe alternatives you've considered**
Tried other actions, they don't support beta projects

**Additional context**

**Comment by leonsteinhaeuser** [comment]
Thank you for your ***feature request***. I'll have a look at this in the next few days.

------

I can confirm that it is not possible to hand over the user as an organization for the automation.

The workflow responds with:
{{{
PROJECT_ID: null
ITEM_ID: 
STATUS_FIELD_ID: 
status_value_OPTION_ID: 
gh: Could not resolve to a node with the global id of 'null'
{data:{updateProjectNextItemField:null},errors:[{type:NOT_FOUND,path:[updateProjectNextItemField],locations:[{line:8,column:9}],message:Could not resolve to a node with the global id of 'null'}]}
}}}

Even if the values ​​are set correctly:
{{{
Run leonsteinhaeuser/project-beta-automations@v1.0.1
  with:
    gh_token: ***
    organization: leonsteinhaeuser
    project_id: ***
    resource_node_id: I_kwDOGWypss4-jzii
    status_value: Todo
}}}

**Comment by leonsteinhaeuser** [comment]
I've finished the first draft for this feature. It worked quite well in my tests. I would like to ask you to take a look at the [README](https://github.com/leonsteinhaeuser/project-beta-automations/blob/feature/user-based-project-support/README.md) file and give me your opinion

**Comment by Mause** [comment]
Works great, thanks!
