### ISSUE TITLE
[Feature Request] map variables against actual project values

### ISSUE THREAD

**Issue by yinonov** [leonsteinhaeuser/project-beta-automations#16]
**Is your feature request related to a problem? Please describe.**
not sure if #9 relates but it is common to change projects status values
e.g.
![image](https://user-images.githubusercontent.com/15140652/144581805-56b56466-62d5-4a69-97ca-89dd4c4adb0f.png)

This breaks the pattern documented in the presented workflow.

**Describe the solution you'd like**
My suggestion is to have variables mapping the values or IDs used in the workflow against the actual ones

`in_progress: In Progress 🚧`

**Additional context**
it might be a no-brainer and a common custom implementation(?)

**Comment by leonsteinhaeuser** [comment]
Hello @yinonov,
thanks for sharing your idea. I'm not sure if this is a good idea since the current setup has the ability to support custom fields. If we add a mapping as you requested, it is not easy to automate custom fields or disable default fields.

**Comment by yinonov** [comment]
The ask is not to change any of the implementation details but the docs to show a use of mapping against the actual custom values.

currently it's a find-and-replace over the original values

**Comment by leonsteinhaeuser** [comment]
Now I understand you. I think you are right that the documentation is missing in some parts and needs further improvement. I will create a PR for these improvements and link it to this issue so you can review it and send me feedback.

**Comment by yinonov** [comment]
gladly!

**Comment by leonsteinhaeuser** [comment]
Hey @yinonov,
I've created a PR, and it would be great if you could take a look.
