### ISSUE TITLE
[Feature Request] hint consumers that some events can be handled by the project workflow

### ISSUE THREAD

**Issue by yinonov** [leonsteinhaeuser/project-beta-automations#21]
some events (e.g. _reopened_) can be handled by the project workflow.
are such triggers redundant in the action example?
![image](https://user-images.githubusercontent.com/15140652/146382899-90e032d3-8956-4cef-856e-d49f81b64dd2.png)

**Comment by leonsteinhaeuser** [comment]
You can define both, but I would personally recommend disabling either the workflows defined by GitHub or the workflows defined in your repository workflow.

**Comment by yinonov** [comment]
utilizing both is truly confusing. Ideally there would be an **_observe repos_** feature (to hook newly opened PRs/issues). paired with "_create and edit own workflow_" settings, it would be possible to rely on the project beta settings alone.

when maintaining multiple repos, the project syncs should be repeated for each.

For now I use actions on repos to add new PRs/issues to the project and from there on out it's the project's workflows handling events
