### ISSUE TITLE
[BUG] status_value is required

### ISSUE THREAD

**Issue by aomarks** [leonsteinhaeuser/project-beta-automations#27]
The documentation states that `status_value` is not required, and that "If left unspecified, new items are added without an explicit status, and existing items are left alone.

However, when running the action without `status_value` set, I get the error `Parameter 1: RESOURCE_NODE_VALUE is not set`.

It looks like this line could be the culprit (it appears to be checking that the variable is not empty): https://github.com/leonsteinhaeuser/project-beta-automations/blob/5d71b8dd89066f3cf88e6ae17c31cc04f8877b70/entrypoint.sh#L64

**Comment by leonsteinhaeuser** [comment]
Thank you very much for this catch. When I introduced the "custom_field" support, I added this check to verify that the user has provided data required to update custom fields. It seems that I forgot the precondition check for the operation_mode custom_field.

**Comment by leonsteinhaeuser** [comment]
@aomarks I have fixed your described problem and created a new release: v1.1.1

If you notice any strange behavior, feel free to reopen this issue.
