### ISSUE TITLE
[BUG] Cross-organization: 'This project item doesn't belong to correct owner'

### ISSUE THREAD

**Issue by CodyCBakerPhD** [leonsteinhaeuser/project-beta-automations#41]
**Describe the bug**
Hi there, we're loving this action so far for automatically adding all Issues/PRs for our organization-owned repositories to our private organization beta projects dashboard.

We'd also love to be able to do this for a handful of repositories that our organization manages, but do not 'own' (they are hosted by other GitHub organizations).

I was hoping that the `organization` field of the YAML would allow for this, but the links to the dashboard do not seem to be going through successfully, with the relevant output of the action (which passes) being:

```
gh: This project item doesn't belong to correct owner
```

**To Reproduce**
Relevant YAML: https://github.com/NeurodataWithoutBorders/nwbinspector/blob/66aa6c995f9151a619aa347bc44f7a19a14a26c5/.github/workflows/add-to-dashboard.yml

The `MY_GITHUB_TOKEN` is setup with permissions and this same workflow works correctly whenever it is used in a repository that organization owns.

Full action output: https://github.com/NeurodataWithoutBorders/nwbinspector/runs/6133081630?check_suite_focus=true

**Expected behavior**
I had hoped it would add the issues/PRs from the external repo to our private organization dashboard. If this isn't supported by this action workflow, just let me know.

**Workflow (please complete the following information):**
 - OS: ubuntu-latest
 - App version: 1.2.1

**Comment by leonsteinhaeuser** [comment]
@CodyCBakerPhD thank you very much for your feedback. Unfortunately, it is currently not supported by GitHub. Personally, I would love to support it as I have use cases for it as well. Currently, both issues and pull requests are tied to a user or organization and therefore it is not possible to reference them. If you are interested in a manual way, you can read this comment: https://github.com/leonsteinhaeuser/project-beta-automations/issues/40#issuecomment-1104824458

**Comment by CodyCBakerPhD** [comment]
@leonsteinhaeuser OK, thanks for the fast response.

> If you are interested in a manual way, you can read this comment: https://github.com/leonsteinhaeuser/project-beta-automations/issues/40#issuecomment-1104824458

Haha, yeah that is indeed what we've been using instead. Not the best, but it's all we have ATM. Maybe I'll bring it up on the Projects (beta) discussion board.
