### ISSUE TITLE
[Feature Request] Add custom label while adding issue to a board

### ISSUE THREAD

**Issue by sumedhpd** [leonsteinhaeuser/project-beta-automations#43]
My use case is we have been using separate Project beta boards for subteams and I'm trying to create a consolidated main board. I still would like the subteams to be able to use the new consolidated board without extra noise and I'm hoping to they can use label filters to get a similar view. In order for this to work seamlessly however, I need the ability to add labels via workflow based on source repo | source board, etc. 

Having the ability to define an extra variable e.g. 'add_labels' should unlock this use case.
Thank you!

**Comment by leonsteinhaeuser** [comment]
Not sure if I understand you correctly, but should these labels be added to the PR/Issue that is managed by this workflow?

**Comment by zoebosschaart** [comment]
@sumedhpd I would suggest to use a separate workflow that manages those labels for you. In my team we have separated those workflows, to keep a clear overview and there are lots of examples already out there :)

**Comment by leonsteinhaeuser** [comment]
@sumedhpd I hope you agree with the solution presented by @zoebosschaart.

**Comment by leonsteinhaeuser** [comment]
I'm closing this issue for now.
