### ISSUE TITLE
[Feature Request] Update to issue form

### ISSUE THREAD

**Issue by scarf005** [leonsteinhaeuser/project-beta-automations#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
[issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) allows interactive issue template. let's use it!

**Describe alternatives you've considered**

**Additional context**

**Comment by leonsteinhaeuser** [comment]
@scarf005 I have added a few forms as PR. Please take a look and give feedback if you would like to see it.
