### ISSUE TITLE
[ BUG ]: Incomplete Architecture Support

### ISSUE THREAD

**Issue by petrandr** [leonsteinhaeuser/project-beta-automations#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the installation script (deps.sh) for the gh CLI only supports one architecture **amd64**.

This means that users on other architectures e.g. **arm64** will not be able to use this automation.

Follows an example output while running the automation on an **arm64**  runner.

```
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/ubuntu/actions-runner/_work/_temp/2d452a82-5f81-4399-8230-7d5468c9a0cc.sh
/home/ubuntu/actions-runner/_work/_temp/2d452a82-5f81-4399-8230-7d5468c9a0cc.sh: line 1: /usr/local/bin/gh: cannot execute binary file: Exec format error
Error: Process completed with exit code 126.
```

This occurs because the dep.sh installed the wrong arch version (amd64) of the gh cli on an arm64 system.

### Expected Behavior

It is important to enhance the installation script to support a wider range of architectures. By doing so, we can ensure that users on various systems can easily use this automation without encountering architecture-related issues.

The expected behaviour is to extend the script to include support for the aarch64 architecture (for now).

With expanded architecture support, the installation script will automatically detect the system architecture and download the appropriate gh CLI binary for seamless installation.

### Version

v1.0.2

### Which github actions runner are you using?

Linux

### Steps To Reproduce

1. Install GitHub Runner on an arm-based system
2. Register the runner in your account
3. Use the automation

### Relevant log output

```shell
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/ubuntu/actions-runner/_work/_temp/2d452a82-5f81-4399-8230-7d5468c9a0cc.sh
/home/ubuntu/actions-runner/_work/_temp/2d452a82-5f81-4399-8230-7d5468c9a0cc.sh: line 1: /usr/local/bin/gh: cannot execute binary file: Exec format error
Error: Process completed with exit code 126.
```
```


### Additional context:

_No response_

**Comment by leonsteinhaeuser** [comment]
Thank you for this report. Indeed, the support of multiple architectures was not planned at that time. I have seen that you have already taken responsibility for the implementation of this feature.

**Comment by leonsteinhaeuser** [comment]
Please ignore the failed labels thing. I always forget that I need to patch the CI actions.

**Comment by leonsteinhaeuser** [comment]
@petrandr this functionality has been release with version v2.2.0.
